version: '3.8'
services:
  frontend:
    build: .
    container_name: titan_frontend
    ports:
      - "80:80"    
      - "44449:44449"
      - "5008:5008"
    # ASPNETCORE_ENVIRONMENT: "Development"
    volumes:
    #  - ./:./data/
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets 
    